config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/homes/about" => "homes#about", as: "about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    get '/about' => 'homes#about'
    get "customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete", as: "complete"
    resources :customers, only: [:show, :edit, :update]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
    resources :orders, only:[:new, :create, :index, :show]
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'homes' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item, optional: true

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :itmes, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  ## 消費税を求めるメソッド
def with_tax_price
  (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {cannot: 0, waiting: 1, manufacture: 2, complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :genre_id, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
  <div class="container my-5">
    <div class="row">
      <div class="offset-1">
        <h3 class="bg-light">ジャンル編集</h3>
      </div>
    </div>
    <%= form_with model: @genre, url: admin_genre_path do |f| %>
    <div class="row my-5">
      <div class="col-2 font-weight-bold">
          <label>ジャンル名</label>
        </div>
        <div class="col-3">
          <%= f.text_field :name %>
        </div>
        <div class="col-2">
          <%= f.submit "変更を保存", class: "btn btn-success btn-block" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/admin/genres/index.html.erb
  <div class="container my-5">
    <div class="row">
      <div class="offset-1">
        <h3 class="bg-light">ジャンル一覧・追加</h3>
      </div>
    </div>
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <div class="row my-5">
        <div class="col-2 font-weight-bold">
          <label>ジャンル名</label>
        </div>
        <div class="col-3">
          <%= f.text_field :name %>
        </div>
        <div class="col-2">
          <%= f.submit "新規登録", class: "btn btn-success btn-block" %>
        </div>
      </div>
    <% end %>
    <table class="table col-4">
      <thead class="bg-light" align="center">
        <th>ジャンル</th>
        <th></th>
      </thead>
      <% @genres.each do |genre| %>
        <tbody>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-block" %></td>
        </tbody>
      <% end %>
    </table>
  </div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row my-5">
    <h3 class="offset-1 bg-light">商品編集</h3>
  </div>
  <<%= form_with model: @item, url: admin_item_path(@item) do |f| %>
    <div class="row">
        <table class="offset-2 form-table">
          <tbody>
            <tr>
              <th width="200" height="50">商品画像</th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <th height="50">商品名</th>
              <td><%= f.text_field :name, class: "form-control", placeholder: "商品名" %></td>
            </tr>

            <tr>
              <th height="50">商品説明</th>
              <td><%= f.text_area :introduction, class: "form-control", style: "height:150px",  placeholder: "ここに説明文を記述します" %></td>
            </tr>

            <tr>
              <th height="50">ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
            </tr>

            <tr>
              <th height="50">税抜価格</th>
              <td><%= f.text_field :price, class: "form-control", placeholder: "1000" %></td>
              <td>円</td>
            </tr>

            <tr>
              <th height="50">販売ステータス</th>
              <td>
                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active, "販売中", {style: "display: inline-block;"} %>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active, "販売停止中", {style: "display: inline-block;"} %>
              </td>
            </tr>
          </tbody>
        </table>
    </div>
    <div class="row mb-5">
      <div class="offset-4 col-2">
      <%= f.submit "変更を保存" ,class: "btn btn-success btn-lg text-right" %>
      </div>
    </div>
    <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row my-5">
    <div class="offset-1">
      <h3 class="bg-light">商品一覧</h3>
    </div>
    <div class="offset-9">
      <%= link_to new_admin_item_path, class: 'btn btn-outline-dark rounded-circle p-1', style: "width:3rem;height:3rem;" do %>
        <h3>+</h3>
      <% end %>
    </div>
  </div>

  <div class="row">
    <table class="table border-dark">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name ,admin_item_path(item) %></td>
            <td><%= item.price.to_s(:delimited, delimiter: ',') %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == false %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <div class="row my-5">
      <h3 class="bg-light">商品新規登録</h3>
    </div>
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row">
        <table class="offset-2 form-table">
          <tbody>
            <tr>
              <th width="200" height="50">商品画像</th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <th height="50">商品名</th>
              <td><%= f.text_field :name, class: "form-control", placeholder: "商品名" %></td>
            </tr>

            <tr>
              <th height="50">商品説明</th>
              <td><%= f.text_area :introduction, class: "form-control", style: "height:150px",  placeholder: "ここに説明文を記述します" %></td>
            </tr>

            <tr>
              <th height="50">ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
            </tr>

            <tr>
              <th height="50">税抜価格</th>
              <td><%= f.text_field :price, class: "form-control", placeholder: "1000" %></td>
              <td>円</td>
            </tr>

            <tr>
              <th height="50">販売ステータス</th>
              <td>
                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active, "販売中", {style: "display: inline-block;"} %>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active, "販売停止中", {style: "display: inline-block;"} %>
              </td>
            </tr>
          </tbody>
        </table>
    </div>
    <div class="row mb-5">
      <div class="offset-4 col-2">
      <%= f.submit "新規登録" ,class: "btn btn-success btn-lg text-right" %>
      </div>
    </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row my-5">
    <h3 class="offset-1 bg-light">商品詳細</h3>
  </div>
  <div class="row ">
    <div class="col-5">
      <%= image_tag @item.get_image, width: '70%'%>
    </div>
    <table>
      <tr>
        <th width="200" height="50">商品名</th>
        <td><%= @item.name %></tr>
      </tr>
      <tr>
        <th height="50">商品説明</th>
        <td><%= @item.introduction%></td>
      </tr>
      <tr>
        <th height="50">ジャンル</th>
        <td><%= @item.genre.name %></td>
      </tr>
      <tr>
        <th height="50">税込価格</br>(税抜価格)</th>
        <td><%= (@item.price).floor.to_s(:delimited, delimiter: ',') %>（<%= (@item.price*1.1).floor.to_s(:delimited, delimiter: ',') %>）円</td>
      </tr>
      <tr>
        <th height="50">販売ステータス</th>
        <td>
          <% if @item.is_active == false %>
            販売中
          <% else %>
            販売停止中
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="offset-5">
  <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success btn-lg text-right" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="contaner">
  <div class="row my-5">
    <h3 class="offset-1 bg-light">注文履歴詳細</h3>
  </div>
  <div class="col-7">
  <table class="table">
    <tbody>
      <tr>
        <th>購入者</th>
        <td>
          <%= link_to admin_customer_path(@order.customer) do %>
            <%= @order.customer.last_name %>
            <%= @order.customer.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.shipping_address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td></td>
      </tr>
    </tbody>
  </table>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @order_details.each do |order_detail| %>
        <td><%= order_detail.item.name %></td>
        <td><%= (order_detail.total_price).floor.to_s(:delimited, delimiter: ',') %></td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.total_price * order_detail.amount).floor.to_s(:delimited, delimiter: ',') %></td>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
            <%= f.select :making_status, options_from_collection_for_select(OrderDetail.all, :id, :making_status) %>
            <%= f.submit '更新',class:"btn btn-success" %>
          <% end %>
        </td>
      <% end %>
    </tbody>
  </table>

  <table class="table">
    <tbody>
      <tr>
        <th>商品合計</th>
        <tr><%= (@order.billing_amount - @order.postage).to_s(:delimited, delimiter: ',') %>円</tr>
      </tr>
      <tr>
        <th>送料</th>
        <tr><%= @order.postage.to_s(:delimited, delimiter: ',') %></tr>
      </tr>
      <tr>
        <th>請求金額合計</th>
        <td><%= @order.billing_amount.to_s(:delimited, delimiter: ',') %></td>
      </tr>
    </tbody>
  </table>

</div>